version: '3'
services:
  rabbitMq:
    image: rabbitmq:3-management
    container_name: rabbitMq_container
    
  token-service-server:
    container_name: token-service
    image: token-service-server
    build: .
    ports:
      - 8182:8182
