version: '3'
services:

  token:
    container_name: token
    image: token-service
    environment:
      - RABBIT_MQ_HOSTNAME=rabbitMq

networks:
  default:
    external: true
    name: dtupaysystem_default